# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d8cf86ef27e8a044a48417720e6cd5c297833a3fa3f144fa4103498f6e11e06d6fcde098dc267f10bb062e8e8cc0713823f4fd752c8244fea3fb0b2d05acd48f

test:
  secret_key_base: 2e456e96dd1697494f85cb2436086e3ae3bb11e29d0149c37562b3cb1bf55546ed1c564b37ec85caa26bbe741f5a3e2a5a3b93a242693fa5a653c412e9e570a6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
